/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.TP5;

public class App { 

    public static void main(String[] args) {
          int enteros[] ={9,7,8,5,6,0,2,1};
        
      //Ejercicio 1
        algoritmosFundamentales.mostrarExplicaciones();
        //Ejercicio 2
        algoritmosCodigos.insercion(enteros, "ASC");
        algoritmosCodigos.burbuja(enteros);
        algoritmosCodigos.seleccion(enteros);
        algoritmosCodigos.busquedaSecuencial(enteros, 8);
    }
}
